//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jde {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jde.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Queries.
        /// </summary>
        public static string AccountQueries {
            get {
                return ResourceManager.GetString("AccountQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Commodity Quotes.
        /// </summary>
        public static string CashCommodityQuotes {
            get {
                return ResourceManager.GetString("CashCommodityQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Reports.
        /// </summary>
        public static string CashReports {
            get {
                return ResourceManager.GetString("CashReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Transactions.
        /// </summary>
        public static string CashTransactions {
            get {
                return ResourceManager.GetString("CashTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Trades.
        /// </summary>
        public static string ClosingTrades {
            get {
                return ResourceManager.GetString("ClosingTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Indexes.
        /// </summary>
        public static string CompanyIndexes {
            get {
                return ResourceManager.GetString("CompanyIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Exchange Information.
        /// </summary>
        public static string ContractExchangeInfos {
            get {
                return ResourceManager.GetString("ContractExchangeInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Obsolete.
        /// </summary>
        public static string ContractObsolete {
            get {
                return ResourceManager.GetString("ContractObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Order Types.
        /// </summary>
        public static string ContractOrderTypes {
            get {
                return ResourceManager.GetString("ContractOrderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotParse0 {
            get {
                return ResourceManager.GetString("CouldNotParse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Future Quotes.
        /// </summary>
        public static string CurrencyFutureQuotes {
            get {
                return ResourceManager.GetString("CurrencyFutureQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Quotes.
        /// </summary>
        public static string CurrencyQuotes {
            get {
                return ResourceManager.GetString("CurrencyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend Accruals.
        /// </summary>
        public static string DividendAccruals {
            get {
                return ResourceManager.GetString("DividendAccruals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend Ratios.
        /// </summary>
        public static string DividendRatios {
            get {
                return ResourceManager.GetString("DividendRatios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividends.
        /// </summary>
        public static string Dividends {
            get {
                return ResourceManager.GetString("Dividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividends Assigned To Positions.
        /// </summary>
        public static string DividendsAssignedToPositions {
            get {
                return ResourceManager.GetString("DividendsAssignedToPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings.
        /// </summary>
        public static string Earnings {
            get {
                return ResourceManager.GetString("Earnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Statistic Quotes.
        /// </summary>
        public static string EnergyStatisticQuotes {
            get {
                return ResourceManager.GetString("EnergyStatisticQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity Summaries.
        /// </summary>
        public static string EquitySummaries {
            get {
                return ResourceManager.GetString("EquitySummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimates.
        /// </summary>
        public static string Estimates {
            get {
                return ResourceManager.GetString("Estimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Symbols.
        /// </summary>
        public static string ExcludedSymbols {
            get {
                return ResourceManager.GetString("ExcludedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileRecords.
        /// </summary>
        public static string FileRecords {
            get {
                return ResourceManager.GetString("FileRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statements.
        /// </summary>
        public static string FinancialStatements {
            get {
                return ResourceManager.GetString("FinancialStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flex Statements.
        /// </summary>
        public static string FlexStatements {
            get {
                return ResourceManager.GetString("FlexStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Commodity Quotes.
        /// </summary>
        public static string FutureCommodityQuotes {
            get {
                return ResourceManager.GetString("FutureCommodityQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Rate Quotes.
        /// </summary>
        public static string GovernmentRateQuotes {
            get {
                return ResourceManager.GetString("GovernmentRateQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Future Quotes.
        /// </summary>
        public static string IndexFutureQuotes {
            get {
                return ResourceManager.GetString("IndexFutureQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Definitions.
        /// </summary>
        public static string IndustryDefinitions {
            get {
                return ResourceManager.GetString("IndustryDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Accruals.
        /// </summary>
        public static string InterestAccruals {
            get {
                return ResourceManager.GetString("InterestAccruals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Future Quotes.
        /// </summary>
        public static string InterestFutureQuotes {
            get {
                return ResourceManager.GetString("InterestFutureQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Rate Quotes.
        /// </summary>
        public static string MoneyRateQuotes {
            get {
                return ResourceManager.GetString("MoneyRateQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes found in &apos;{0}&apos;..
        /// </summary>
        public static string NoChangesFound0 {
            get {
                return ResourceManager.GetString("NoChangesFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {null}.
        /// </summary>
        public static string NullSymbol {
            get {
                return ResourceManager.GetString("NullSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Positions.
        /// </summary>
        public static string OpenPositions {
            get {
                return ResourceManager.GetString("OpenPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionValues {
            get {
                return ResourceManager.GetString("OptionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type Definitions.
        /// </summary>
        public static string OrderTypeDefinitions {
            get {
                return ResourceManager.GetString("OrderTypeDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Dividends.
        /// </summary>
        public static string PositionDividends {
            get {
                return ResourceManager.GetString("PositionDividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Price Ratios.
        /// </summary>
        public static string PriceRatios {
            get {
                return ResourceManager.GetString("PriceRatios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Ratios.
        /// </summary>
        public static string Ratios {
            get {
                return ResourceManager.GetString("Ratios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Least Squares Regressions.
        /// </summary>
        public static string SingleLeastSquaresRegressions {
            get {
                return ResourceManager.GetString("SingleLeastSquaresRegressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string Snapshots {
            get {
                return ResourceManager.GetString("Snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Index Histories.
        /// </summary>
        public static string StockIndexHistories {
            get {
                return ResourceManager.GetString("StockIndexHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Market Crossing Sessions.
        /// </summary>
        public static string StockMarketCrossingSessions {
            get {
                return ResourceManager.GetString("StockMarketCrossingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Market Diaries.
        /// </summary>
        public static string StockMarketDiaries {
            get {
                return ResourceManager.GetString("StockMarketDiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Market Volume Breakdowns.
        /// </summary>
        public static string StockMarketVolumeBreakdowns {
            get {
                return ResourceManager.GetString("StockMarketVolumeBreakdowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Market Volumes.
        /// </summary>
        public static string StockMarketVolumes {
            get {
                return ResourceManager.GetString("StockMarketVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Option Quotes.
        /// </summary>
        public static string StockOptionQuotes {
            get {
                return ResourceManager.GetString("StockOptionQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Options.
        /// </summary>
        public static string StockOptions {
            get {
                return ResourceManager.GetString("StockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quotes.
        /// </summary>
        public static string StockQuotes {
            get {
                return ResourceManager.GetString("StockQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Raters.
        /// </summary>
        public static string StockRaters {
            get {
                return ResourceManager.GetString("StockRaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Rating Changes.
        /// </summary>
        public static string StockRatingChanges {
            get {
                return ResourceManager.GetString("StockRatingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Rating Maps.
        /// </summary>
        public static string StockRatingMaps {
            get {
                return ResourceManager.GetString("StockRatingMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Short Interest Snapshots.
        /// </summary>
        public static string StockShortInterestSnapshots {
            get {
                return ResourceManager.GetString("StockShortInterestSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Splits.
        /// </summary>
        public static string StockSplits {
            get {
                return ResourceManager.GetString("StockSplits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS Quotes.
        /// </summary>
        public static string TipsQuotes {
            get {
                return ResourceManager.GetString("TipsQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Offsets.
        /// </summary>
        public static string TradeOffsets {
            get {
                return ResourceManager.GetString("TradeOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades.
        /// </summary>
        public static string Trades {
            get {
                return ResourceManager.GetString("Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts.
        /// </summary>
        public static string UserAccounts {
            get {
                return ResourceManager.GetString("UserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Changes.
        /// </summary>
        public static string ValueChanges {
            get {
                return ResourceManager.GetString("ValueChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Histories.
        /// </summary>
        public static string WebsiteHistories {
            get {
                return ResourceManager.GetString("WebsiteHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website History Exclusions.
        /// </summary>
        public static string WebsiteHistoryExclusions {
            get {
                return ResourceManager.GetString("WebsiteHistoryExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string Websites {
            get {
                return ResourceManager.GetString("Websites", resourceCulture);
            }
        }
    }
}
